version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  listing-service:
    build: .
    container_name: listing-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/listingService
      - AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_KEY
      - AWS_REGION=YOUR_AWS_REGION
      - S3_BUCKET_NAME=YOUR_S3_BUCKET_NAME
      - WORKFLOW_SERVICE_URL=https://workflow-service.example.com
      - NOTIFICATION_SERVICE_URL=https://notification-service.example.com
    ports:
      - "6000:6000"
    depends_on:
      - mongo

volumes:
  mongo-data:

